//
//  IDPTagStyleKit.h
//  IDPTaggingParseServer
//
//  Created by Kaname Noto on 2016/11/29.
//  Copyright (c) 2016 Irimasu Densan Planning. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface IDPTagStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tagInformationTargets;

// Drawing Methods
+ (void)drawHeaderBackGroundWithFrame: (CGRect)frame;
+ (void)drawCheckColor;

// Generated Images
+ (UIImage*)imageOfTagInformation;

@end
